import argparse


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="DeepSpeech training")
    parser.add_argument("--sample-rate", default=16000, type=int)
    parser.add_argument("--num-workers", default=32, type=int)
    parser.add_argument("--window-size", default=0.02, type=float)
    parser.add_argument("--window-stride", default=0.01, type=float)
    parser.add_argument("--window", default="hamming")
    parser.add_argument("--hidden-size", default=480, type=int)
    parser.add_argument("--hidden-layers", default=4, type=int)
    parser.add_argument("--rnn-type", default="gru", choices=["gru", "lstm", "rnn"])
    parser.add_argument("--epochs", default=1000, type=int)
    parser.add_argument("--cuda", action="store_true", default=False)
    parser.add_argument("--lr", default=3e-4, type=float)
    parser.add_argument("--momentum", default=0.9, type=float)
    parser.add_argument("--max-norm", default=400, type=int)
    parser.add_argument("--learning-anneal", default=1.005, type=float)
    parser.add_argument("--silent", action="store_true")
    parser.add_argument("--tensorboard", action="store_true")
    parser.add_argument("--log-dir", default="visualize/deepspeech_final")
    parser.add_argument("--log-params", action="store_true")
    parser.add_argument("--id", default="DeepSpeech training")
    parser.add_argument("--finetune", action="store_true")
    parser.add_argument("--speed-volume-perturb", action="store_true")
    parser.add_argument("--spec-augment", action="store_true")
    parser.add_argument("--noise-dir", default=None)
    parser.add_argument("--noise-prob", default=0.4, type=float)
    parser.add_argument("--noise-min", default=0.0, type=float)
    parser.add_argument("--noise-max", default=0.5, type=float)
    parser.add_argument("--no-shuffle", action="store_true")
    parser.add_argument("--no-bidirectional", dest="bidirectional", action="store_false", default=True)
    parser.add_argument("--seed", default=123456, type=int)
    parser.add_argument("--train-manifest", metavar="DIR")
    parser.add_argument("--val-manifest", metavar="DIR")
    parser.add_argument("--model-path", default="models/deepspeech_final.pth")
    return parser


def add_decoder_args(parser: argparse.ArgumentParser) -> argparse.ArgumentParser:
    g = parser.add_argument_group("Beam Decode Options")
    g.add_argument("--top-paths", default=1, type=int)
    g.add_argument("--beam-width", default=10, type=int)
    g.add_argument("--lm-path", default=None, type=str)
    g.add_argument("--alpha", default=0.8, type=float)
    g.add_argument("--beta", default=1.0, type=float)
    g.add_argument("--cutoff-top-n", default=40, type=int)
    g.add_argument("--cutoff-prob", default=1.0, type=float)
    g.add_argument("--lm-workers", default=1, type=int)
    return parser
